### ISSUE TITLE
[BUG] Cookiecutter crashes on Windows

### ISSUE THREAD

**Issue by chisholm** [usnistgov/dioptra#261]
**Describe the bug**

Cookiecutter fails on Windows, on dev branch.  There are a couple problems; this issue collects descriptions of both problems together.

1. There is a text encoding related crash:

```
>cookiecutter .\cookiecutter-dioptra-deployment
...

DEBUG:post_gen_project:Current working directory: ...\dioptra\cookiecutter-templates\dioptra-deployment
INFO:post_gen_project:Scanning files and replacing the "$((BASEDIR))" symbol with ...\dioptra\cookiecutter-templates\dioptra-deployment
Traceback (most recent call last):
  File "C:\Users\chisholm\AppData\Local\Temp\tmpbbmdui97.py", line 188, in <module>
    render_absolute_path_to_base_directory()
  File "C:\Users\chisholm\AppData\Local\Temp\tmpbbmdui97.py", line 115, in render_absolute_path_to_base_directory
    data = f.read()
           ^^^^^^^^
  File "C:\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 9654: character maps to <undefined>
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

2. There is a Jinja2 crash, when inserting generated passwords.

In order to get far enough to encounter this issue, I have to hand-edit the post-gen hook script to get past issue (1) above, and change password generation so it doesn't rely on a dictionary word file which is not present on Windows.  After having done that, the following results:

```
...
INFO:post_gen_project:Generating "Correct Horse Battery Staple" passwords
INFO:post_gen_project:Inserting generated passwords in file: secrets\postgres-passwd.env
Traceback (most recent call last):
  File "C:\Users\chisholm\AppData\Local\Temp\tmpnggvckp8.py", line 190, in <module>
    insert_random_passwords(PASSWORD_FILES, WORDS_FILE, JINJA_ENV)
  File "C:\Users\chisholm\AppData\Local\Temp\tmpnggvckp8.py", line 93, in insert_random_passwords
    content = _render_template(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\chisholm\AppData\Local\Temp\tmpnggvckp8.py", line 124, in _render_template
    template = env.get_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programming\python\dioptra\venv311\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programming\python\dioptra\venv311\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programming\python\dioptra\venv311\Lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programming\python\dioptra\venv311\Lib\site-packages\jinja2\loaders.py", line 195, in get_source
    pieces = split_template_path(template)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programming\python\dioptra\venv311\Lib\site-packages\jinja2\loaders.py", line 36, in split_template_path
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: secrets\postgres-passwd.env
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

**To Reproduce**
1. Run cookiecutter on the dioptra template

**Expected behavior**

It completes without crashing

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

For (1), there needs to be some explicit encodings given.  For example:

https://github.com/usnistgov/dioptra/blob/afac48b552ef6f888845c0397efaf8a68393e149/cookiecutter-templates/cookiecutter-dioptra-deployment/hooks/post_gen_project.py#L114

The above code doesn't give an encoding.  The file being read is utf-8 encoded, with a lot of multi-byte encoded characters.  The default on windows is cp1252, which causes the crash.

For (2), the cause is the use of pathlib, which causes violation of the requirements for `env.get_template(...)`.  The way the template names are constructed in the hook script, they have backslashes on Windows, which is incorrect.  Jinja2's [documentation](https://jinja.palletsprojects.com/en/3.1.x/api/#jinja2.Environment.get_template) says for the `name` parameter: "When loading templates from the filesystem, “/” is used as the path separator, *even on Windows*."

**Comment by jkglasbrenner** [comment]
Closed by #262
